### ISSUE TITLE
Updating svg icons?

### ISSUE THREAD

**Issue by gusreyes01** [nelyousfi/FloatingMenuReactNative#1]
@nelyousfi thanks for putting this project together. I was wondering if there's different svg icons I could use instead of the ones on the demo. I tried copying a different path from another icon into the Path markup but it didn't work.

Thank you!

**Comment by nelyousfi** [comment]
@gusreyes01 Hello. Yep of course all u have to do is to copy the icon's path into `menus.js` and it should be working! If it did not, u can send me the icon and I can give a try by myself.

**Comment by gusreyes01** [comment]
Thanks for the quick response!

Here's a path I've tried without success. It just renders blank:

	<path d="M188.5,270.3c-24.4,28.1-23.2,71.7,2.6,98.6c14.4,15.1,33.7,22.6,52.9,22.6c18.8,0,37.5-7.2,51.8-21.5
			c6.5-6.5,11.6-14,15.1-21.9l0,0l94.5-183.2c2.5-5.2-2.9-10.6-8.1-8.1l-183.2,94.5l0,0C204.6,255.5,195.9,261.9,188.5,270.3z
			 M221.9,296.1c6.1-6.1,14.1-9.2,22.1-9.2s16,3.1,22.2,9.2c12.2,12.2,12.2,32.1,0,44.3c-6.1,6.1-14.1,9.2-22.2,9.2
			c-8,0-16-3.1-22.1-9.2C209.6,328.1,209.6,308.3,221.9,296.1z M440.2,341.4c0-34.6-9.1-68.6-26.4-98.3c-6.7-11.6-2.8-26.4,8.8-33.1
			c11.6-6.7,26.4-2.8,33.1,8.8c21.5,37.1,32.9,79.5,32.9,122.6c0,13.4-10.8,24.2-24.2,24.2C451.1,365.6,440.2,354.8,440.2,341.4z
			 M0,341.4C0,206.7,109.6,97.1,244.3,97.1c31.3,0,61.8,5.8,90.6,17.4c12.4,5,18.4,19,13.5,31.4c-5,12.4-19,18.4-31.4,13.5
			c-23.1-9.2-47.6-13.9-72.7-13.9c-108,0-195.9,87.9-195.9,195.9c0,13.4-10.8,24.2-24.2,24.2C10.8,365.6,0,354.8,0,341.4z"/>

I'm trying to set a speedometer icon. If you could share the reference where you got your icons from I can probably pull them from there.

**Comment by nelyousfi** [comment]
I guess what u are missing is `viewBox={'0 0 your_SGV_width your_SVG_height'}` but I guess u need to tweak the stroke as well with the same ratio.

What I suggest is this, download the SVG file, open it with Gimp, then change the width and height to 24 and select import paths and merge them then do export path in the paths dialog.

<img width="534" alt="Screen Shot 2019-09-01 at 12 25 49 AM" src="https://user-images.githubusercontent.com/26110116/64069695-41353700-cc4f-11e9-8898-ce0e2e5ad815.png">

<img width="243" alt="Screen Shot 2019-09-01 at 12 26 03 AM" src="https://user-images.githubusercontent.com/26110116/64069706-675ad700-cc4f-11e9-81bc-905de03f4b84.png">

Then open the exported SVG file with any text editor and copy the path.

Like this u will have the height and width as your viewBox so need to specify it.

**Comment by nelyousfi** [comment]
By the way this an SVG icon of a speedometer that works:
```
<Svg width={24} height={24}>
  <Path fill={'none'} stroke={'black'} strokeWidth={1} d="M 12.00,0.00 C 5.38,0.00 0.00,5.38 0.00,12.00 0.00,18.62 5.38,24.00 12.00,24.00 18.62,24.00 24.00,18.62 24.00,12.00 24.00,5.38 18.62,0.00 12.00,0.00 Z M 12.00,1.00 C 18.06,1.00 23.00,5.94 23.00,12.00 23.00,14.64 22.06,17.06 20.51,18.96 18.51,16.27 15.36,14.68 12.00,14.68 11.52,14.68 11.05,14.71 10.58,14.77 10.58,14.77 8.97,7.90 8.97,7.90 8.97,7.90 7.99,8.13 7.99,8.13 7.99,8.13 9.59,14.95 9.59,14.95 7.16,15.52 5.00,16.92 3.49,18.96 1.94,17.06 1.00,14.64 1.00,12.00 1.00,5.94 5.94,1.00 12.00,1.00 Z M 12.00,23.00 C 8.94,23.00 6.18,21.74 4.18,19.72 5.98,17.18 8.86,15.68 12.00,15.68 15.11,15.68 18.02,17.19 19.82,19.72 17.82,21.74 15.06,23.00 12.00,23.00 Z M 12.50,4.38 C 12.50,4.38 11.50,4.38 11.50,4.38 11.50,4.38 11.50,2.75 11.50,2.75 11.50,2.75 12.50,2.75 12.50,2.75 12.50,2.75 12.50,4.38 12.50,4.38 Z M 4.38,12.50 C 4.38,12.50 2.75,12.50 2.75,12.50 2.75,12.50 2.75,11.50 2.75,11.50 2.75,11.50 4.38,11.50 4.38,11.50 4.38,11.50 4.38,12.50 4.38,12.50 4.38,12.50 4.38,12.50 4.38,12.50 Z M 21.25,12.50 C 21.25,12.50 19.62,12.50 19.62,12.50 19.62,12.50 19.62,11.50 19.62,11.50 19.62,11.50 21.25,11.50 21.25,11.50 21.25,11.50 21.25,12.50 21.25,12.50 21.25,12.50 21.25,12.50 21.25,12.50 Z M 6.26,6.97 C 6.26,6.97 5.10,5.81 5.10,5.81 5.10,5.81 5.81,5.10 5.81,5.10 5.81,5.10 6.97,6.26 6.97,6.26 6.97,6.26 6.26,6.97 6.26,6.97 Z M 17.74,6.97 C 17.74,6.97 17.03,6.26 17.03,6.26 17.03,6.26 18.19,5.10 18.19,5.10 18.19,5.10 18.90,5.81 18.90,5.81 18.90,5.81 17.74,6.97 17.74,6.97 Z" />
</Svg>
```

**Comment by gusreyes01** [comment]
@nelyousfi That last path is exactly what I needed. If I need additional icons in the future I'm sure the Gimp technique will work. Thank you so much for your time!

**Comment by nelyousfi** [comment]
@gusreyes01 Great to hear, good luck.
I will close this issue.
